
package org.apache.ode.pmapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InstanceManagementService", targetNamespace = "http://www.apache.org/ode/pmapi", wsdlLocation = "file:/C:/Users/K5007843/Desktop/11%20wsdl/InstanceManagement.wsdl")
public class InstanceManagementService
    extends Service
{

    private final static URL INSTANCEMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException INSTANCEMANAGEMENTSERVICE_EXCEPTION;
    private final static QName INSTANCEMANAGEMENTSERVICE_QNAME = new QName("http://www.apache.org/ode/pmapi", "InstanceManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/K5007843/Desktop/11%20wsdl/InstanceManagement.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSTANCEMANAGEMENTSERVICE_WSDL_LOCATION = url;
        INSTANCEMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public InstanceManagementService() {
        super(__getWsdlLocation(), INSTANCEMANAGEMENTSERVICE_QNAME);
    }

    public InstanceManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSTANCEMANAGEMENTSERVICE_QNAME, features);
    }

    public InstanceManagementService(URL wsdlLocation) {
        super(wsdlLocation, INSTANCEMANAGEMENTSERVICE_QNAME);
    }

    public InstanceManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSTANCEMANAGEMENTSERVICE_QNAME, features);
    }

    public InstanceManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InstanceManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InstanceManagementPortType
     */
    @WebEndpoint(name = "InstanceManagementPort")
    public InstanceManagementPortType getInstanceManagementPort() {
        return super.getPort(new QName("http://www.apache.org/ode/pmapi", "InstanceManagementPort"), InstanceManagementPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InstanceManagementPortType
     */
    @WebEndpoint(name = "InstanceManagementPort")
    public InstanceManagementPortType getInstanceManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.apache.org/ode/pmapi", "InstanceManagementPort"), InstanceManagementPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSTANCEMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw INSTANCEMANAGEMENTSERVICE_EXCEPTION;
        }
        return INSTANCEMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
