
package org.apache.ode.pmapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessManagementService", targetNamespace = "http://www.apache.org/ode/pmapi", wsdlLocation = "file:/C:/Users/K5007843/Desktop/11%20wsdl/InstanceManagement.wsdl")
public class ProcessManagementService
    extends Service
{

    private final static URL PROCESSMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSMANAGEMENTSERVICE_EXCEPTION;
    private final static QName PROCESSMANAGEMENTSERVICE_QNAME = new QName("http://www.apache.org/ode/pmapi", "ProcessManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/K5007843/Desktop/11%20wsdl/InstanceManagement.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSMANAGEMENTSERVICE_WSDL_LOCATION = url;
        PROCESSMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public ProcessManagementService() {
        super(__getWsdlLocation(), PROCESSMANAGEMENTSERVICE_QNAME);
    }

    public ProcessManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSMANAGEMENTSERVICE_QNAME, features);
    }

    public ProcessManagementService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSMANAGEMENTSERVICE_QNAME);
    }

    public ProcessManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSMANAGEMENTSERVICE_QNAME, features);
    }

    public ProcessManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessManagementPortType
     */
    @WebEndpoint(name = "ProcessManagementPort")
    public ProcessManagementPortType getProcessManagementPort() {
        return super.getPort(new QName("http://www.apache.org/ode/pmapi", "ProcessManagementPort"), ProcessManagementPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessManagementPortType
     */
    @WebEndpoint(name = "ProcessManagementPort")
    public ProcessManagementPortType getProcessManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.apache.org/ode/pmapi", "ProcessManagementPort"), ProcessManagementPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw PROCESSMANAGEMENTSERVICE_EXCEPTION;
        }
        return PROCESSMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
